language: python
python:
  - "3.6"
sudo: enabled
notifications:
  email: false
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install pylint
# command to test
script:
  - lintRes=$(pylint python_sources/ | egrep -o '(?:rated at )(\d+\.?\d*)' | egrep -o '(\d+\.?\d*)')
  - if (( $(echo "$lintRes < 8" | bc -l) )); then echo Linting score to low: $res. Failing; (exit1);fi;

