language: python
python:
  - "3.6"
sudo: enabled
notifications:
  email: false
# command to install dependencies
install:
  - pip install git+https://github.com/BPChain/scenario-orchestration-service.git
  - pip install git+https://github.com/BPChain/blockchain_statistics_readout.git
  - pip install -r requirements.txt
  - pip install pylint
# command to test
script:
  - pylint python_sources

