language: python
python:
  - "3.6"
sudo: enabled
notifications:
  email: false
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install pylint
# command to test
script:
  - lintRes=$(pylint python_sources/ | grep -E -o '(?:rated at )(\d+\.?\d*)' | grep -E -o '(\d+\.?\d*)')
  - echo $lintRes

