version: '2'
services:
    masternode:
      build: .
      stdin_open: true
      tty: true
      networks:
        - multichain-net
      ports:
        - "20000:20000"
      entrypoint: /masterEntry.sh
      environment:
        TARGET_HOSTNAME: ${HOSTNAME}
    slavenode:
      build: .
      stdin_open: true
      tty: true
      networks:
        - multichain-net
      entrypoint: /slaveEntry.sh
      environment:
        TARGET_HOSTNAME: ${HOSTNAME}

networks:
  multichain-net:
    driver: bridge
