version: '2'
services:
    masternode:
      build: .
      stdin_open: true
      tty: true
      networks:
        - multichain-net
      entrypoint: /masterEntry.sh
    slavenode:
      build: .
      stdin_open: true
      tty: true
      networks:
        - multichain-net
      entrypoint: /slaveEntry.sh

networks:
  multichain-net:
    driver: bridge
