version: '2'
services: 
    masternode: 
      build: .
      stdin_open: true
      tty: true
      entrypoint: /masterEntry.sh
    slavenode: 
      build: .
      links: 
        - masternode
      stdin_open: true
      tty: true
      entrypoint: /slaveEntry.sh

